### ISSUE TITLE
Bionic Reading Not Working (f/u on AnkiWeb Review)

### ISSUE THREAD

**Issue by dscottwu** [AnKing-VIP/anki-bionic-reading#9]
#### Problem description

Downloaded Bionic Reading on the latest version of Anki. Does not work. Immediate error message on boot up. Bug information pasted forward below. When error message is ignored, any card types toggled immediately are unchecked even after saving.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.5-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/davidscottwu/Library/Application Support/Anki2/addons21/649714433/config.py", line 60, in on_click
    add_script_to_all_note_types()
  File "/Users/davidscottwu/Library/Application Support/Anki2/addons21/649714433/notetype.py", line 54, in add_script_to_all_note_types
    mw.col.models.update_dict(note_type)
  File "anki.models", line 226, in update_dict
  File "anki._backend_generated", line 1065, in update_notetype_legacy
  File "anki._backend", line 166, in _run_command
anki.errors.CardTypeError: Card template ⁨3⁩ in notetype '⁨A. Artery⁩' has a problem.<br>Expected to find a field replacement on the front of the card template.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T11:01, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-07-18T08:41, 'None', mod]
AnkiConnect ['2055492159', 2024-06-17T21:37, 'None', mod]
AnkiHub ['1322529746', 2024-07-09T12:26, 'None', mod]
Bionic Reading ['649714433', 2023-10-26T16:24, 'None', mod]
Exam Notifier ['236593452', 2023-01-19T11:12, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-07-09T07:54, 'None', '']
Filtered deck from browser selection - study review cards in browser order ['127393092', 2023-03-19T13:02, 'None', '']
Life Drain ['715575551', 2024-04-30T02:15, 'None', mod]
More Decks Stats and Time Left ['1556734708', 2024-04-11T05:35, 'None', '']
Postpone cards review ['1152543397', 2023-04-14T21:29, 'None', '']
Progress Bar original ['1685464019', 2022-07-28T00:24, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
Special Fields ['1102281552', 2024-03-19T18:34, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T05:24, 'None', '']
True Retention ['613684242', 2017-11-19T14:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1102281552 1152543397 127393092 1322529746 1556734708 1685464019 1771074083 2055492159 236593452 613684242 649714433 715575551 759844606 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Killstreaks ['579111794', 2021-12-15T09:20, 'None', '']
Straight Reward ['957961234', 2023-11-01T09:11, 'None', '']

```

**Comment by BlueGreenMagick** [comment]
It's because your notetype already has a problem. 

In toolbar, go to ' Tools > Manage Note Types '.
Select 'A. Artery' notetype and click 'Cards...' button.
In the card type editor, change 'Card Type' to the 3rd template.
In Front template, you need to add a field replacement. (e.g. `{{Front}}`)

See #6 for detailed description

**Comment by dscottwu** [comment]
Fixed by copy-pasting <script src="_bionic-reading.js"></script> into note types. Thanks!
